# Generated by Django 5.2 on 2025-05-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labreport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='lab_reports/'),
        ),
    ]
