# Generated by Django 5.2 on 2025-05-08 12:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_patientregister_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tablets', models.JSONField(blank=True, default=list)),
                ('tabletsAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('injections', models.JSONField(blank=True, null=True)),
                ('injectionsAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ointments', models.JSONField(blank=True, null=True)),
                ('ointmentsAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('syrups', models.JSONField(blank=True, null=True)),
                ('syrupsAmount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_tests', to='api.patientregister')),
            ],
        ),
    ]
